### ISSUE TITLE
Exemplo de docker-compose para WordPress

### ISSUE THREAD

**Issue by saulopaiva** [webfatorial/wp-apache-dev-docker-image#1]
Exemplo de docker-compose para WordPress.

1. Altere a palavra `project` pelo nome de seu projeto.
2. Baixe a versão desejada do WordPress.
3. Adicione no hosts da máquina `127.0.0.1 http://project.local` e acesse o browser para instalação do projeto.

```
version: "3.7"

services:
  wordpress:
    image: webfatorial/wp-apache-dev
    environment:
      - DB_HOST=mysql
      - DB_NAME=project
      - DB_PASSWORD=project
      - DB_USER=project
      - WP_HOME=http://project.local
      - WP_SITEURL=http://project.local
      - DEV=true
    ports:
      - 80:80
    volumes:
      - .:/var/www/html/web
    depends_on:
      - mysql
    working_dir: /var/www/html/web

  mysql:
    image: mysql:5.7
    ports:
      - 3306:3306
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=true
      - MYSQL_USER=project
      - MYSQL_PASSWORD=project
      - MYSQL_DATABASE=project
    volumes:
      - database-volume:/var/lib/mysql
      - ./dumps:/docker-entrypoint-initdb.d

  cli:
    image: wordpress:cli-php7.3
    environment:
      - DB_HOST=mysql
      - DB_NAME=project
      - DB_PASSWORD=project
      - DB_USER=project
      - WP_HOME=http://project.local
      - WP_SITEURL=http://project.local
      - DEV=true
    volumes:
      - .:/var/www/html/web
    depends_on:
      - wordpress
    working_dir: /var/www/html/web

volumes:
  database-volume:
```
